### ISSUE TITLE
EV Charging

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1127]
Add charging behavior for personally owned EVs.

**Comment by robfitzgerald** [comment]
In order to begin this work, the following changes need to be made:

1. Add "Car" vehicle type in the last column of the __vehicleTypes.csv__ file (the column _vehicleCategory_). this overrides _something_ to _do some magic stuff_.
2. Replace the function _getMode_ in BeamVehicleType.scala (line 120) with: 
```scala
def getMode(beamVehicle: BeamVehicle): BeamMode = {
  beamVehicle.beamVehicleType.vehicleCategory match {
    //TODO complete list
  case Some(Bike) => BIKE
    case Some(RideHail) => RIDE_HAIL
    case Some(Car) => CAR
  }
```

**Comment by rjf-nrel** [comment]
Question.

In the ZonalParkingManager, we inspect the ParkingPreference of an inquiry in order to constrain our search to Residential, Workplace, or Public spots. Assuming we want to do something similar here for charging. Does this user story include implementing a heuristic or modal logic for mapping ChargingPreference (and maybe something about the vehicle spec too) to a ChargingType?

**Comment by robfitzgerald** [comment]
Another (ZonalParkingManager) question.

Currently, after searching for parking stalls, we find the optimal stall via a ranking function. that function is:

```scala
val cost  +  attrib.pricingModel match {
      case FlatFee => feeInCents.toDouble / 100.0
      case Block   => parkingDuration / 3600.0 * (feeInCents.toDouble / 100.0)
    }
val valueOfTimeSpentWalking = walkingDistance / 1.4 / 3600.0 * inquiry.attributesOfIndividual.valueOfTime
val ranking = cost + valueOfTimeSpentWalking
```

Should some aspect of charging be integrated into the cost function (when applicable)? This is used the DepotParkingInquiry logic:

```scala
ChargingType.getChargerPowerInKW(chargingType)
```
