### ISSUE TITLE
No route found debugging

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#114]
No alternatives found and ResourceCapacityExhausted are the two 2.

**Comment by michaz** [comment]
"No alternatives found" appears to be because of hard-coded limits on trip length and maximum walking time, respectively.

**Comment by sfwatergit** [comment]
Thanks. Could you elaborate on that observation a bit? If these are
variable, then search may take exceedingly long. This was essentially the
case when we used the defaults. We have considered using a heuristic to
parameterize these values.

**Comment by colinsheppard** [comment]
Would if we take the Euclidean distance multiplied by some factor tuned for each type of limit?

**Comment by michaz** [comment]
> This was essentially the
case when we used the defaults. We have considered using a heuristic to
parameterize these values.

Ah, I see. I'm proposing ``Integer.MAX_VALUE`` here since we were discussing a hard guarantee on the router to return a walk alternative and I'm naive about performance so far..

**Comment by michaz** [comment]
How can I regression-test the performance?

**Comment by colinsheppard** [comment]
We haven't devised a test for this, but just timing how long to route X trips with without the expanded search distance would do the trick, just make sure they're all able to actually route in both cases.

**Comment by wrashid** [comment]
@michaz Does setting trip length and max walking timing to Integer.MAX_VALUE remove the "No alternatives found" totally from the application sfbay sceanrio?

**Comment by michaz** [comment]
@wrashid I can't run it to completion, but it seems so. Also, R5 now prints fewer warnings. Before, it was complaining about resource limits being algorithmically unsound when optimizing for something else.

**Comment by sfwatergit** [comment]
@michaz in the perfmon branch, I've begun integrating Kamon-based
performance metrics. Eventually, we can use Kamon to collect stats on the
router in order to manage performance. I think this will be much more
robust, flexible, and informative than a home-baked solution at this point,
although I could think of several ways this could be done in a pretty
simple manner.

Another solution is to set the max walk/trip length to Integer.MAX_VALUE,
but set an upper limit on the response time for the actor. I think this can
be done either using Promises and Futures... However, I'm not sure how to
cancel the actual request in R5 once the expiry condition is reached.

**Comment by michaz** [comment]
When I just use the regular R5 network, it appears that the only remaining "no alternatives"-cases are the ride hailers.

**Comment by colinsheppard** [comment]
Not sure I follow. If ride haling fails, we still would ideally have a fallback route from R5 (e.g. walking) in all cases where it's physically possible.

**Comment by michaz** [comment]
Oookay, now we have an agent who *actually* can't walk because it wants over the bridge and the bridge isn't walkable. Google doesn't use it either:

https://www.google.com/maps/dir/'37.9179853,-122.4837232'/37.9593399,-122.4236571/@37.863602,-122.439585,11.06z/data=!3m1!4b1!4m7!4m6!1m3!2m2!1d-122.4837232!2d37.9179853!1m0!3e2

**Comment by michaz** [comment]
Fixed this (for now?) by re-introducing a maximum walk time into the request to R5, and if R5 doesn't find such a solution, return a fallback "solution" with that walk time anyway.

As @colinsheppard suggested, we can set this limit as a function of the beeline distance. This _could_ be modelled as an extra mode, distinct from walking, so it can be picked up in analysis. Kai Nagel calls it bushwhacking.

**Comment by michaz** [comment]
Every person gets a walk alternative now, bushwhacking or otherwise.
