### ISSUE TITLE
Enable Test Suite on Travis

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#118]
even if they are failing, let's start running them.

**Comment by zishanbilal** [comment]
Tests are configured on this branch and as we merge it to other it would work for target branch as well. As i enables the scala tests suite build start crashing, i recommend to resolve failed test before merging it to other branches.

**Comment by michaz** [comment]
I just went through the tests on application-sfbay. Fixed some of them. Just changes in dynamic constructor arguments of Actors and such.

In the process, I started avoiding passing BeamServices to Actors, as discussed, when e.g. the Config (which is immutable) would be enough.

Some other tests, I set to ignore, because they not only do not run, but hang in an infinite loop. Those need attention, because those are precisely the tests which in fact look interesting. :-)

**Comment by michaz** [comment]
> but hang in an infinite loop

Which was previously masked by an exception which is fixed now.

**Comment by michaz** [comment]
Okay, maybe loading the sfbay scenario *is* a bit much for Travis. :-(

**Comment by zishanbilal** [comment]
I had integrated Travis with AWS CodeDeploy to run such large tests and integration test, right now that part is commented. If its desired, i can enable that again and fix if anything breaking with new changes. We can publish the report to s3 or some tool as well.

**Comment by michaz** [comment]
(We now think that using the sf-light scenario for continuous testing is fine.)
