### ISSUE TITLE
disable modestats plot and text file

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1319]
"modestats.txt" is redundant with modeChoice and because it is a MATSim process, it doesn't capture the new modes we have added in BEAM.

This should be easily done by binding ModeStatsControlerListener to some new implementation class that doesn't do anything.

**Comment by bhavyalatha26** [comment]
@colinsheppard when I try to extend the ModeStatsControlerListener to created a mocked / dummy listener , it throws an error. 
**constructor ModeStatsControlerListener in class ModeStatsControlerListener cannot be accessed in class MockModeStatsControlerListener**

**Comment by bhavyalatha26** [comment]
Hi @colinsheppard 

ModeStatsControlerListener invokes the creation of modestats text and png files in the constructor itself. And there is no default constructor for this class.

Now since the mocked class extends the ModeStatsControlerListener, it automatically invokes the constructor of while creating the instance of the mocked class , which essentially breaks the whole idea of implementing this mocked class.
