### ISSUE TITLE
Add MAXRAM to step-by-step

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1339]
In the getting started guide, we need to inform users that they should set MAXRAM in an environment variable and choose a value based on their system.

**Comment by bhavyalatha26** [comment]
@bhavyalatha26  more context on the MAXRAM issue I just created (from a user / developer): 

Hi Colin, 
I found a small problem with the step-by-step guide. When running (as listed here): 
```bash
./gradlew :run -PappArgs="['--config', 'test/input/beamville/beam.conf']" 
```

I get the error: 
```
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f67bd000000, 50108301312, 0) failed; error='Cannot allocate memory' (errno=12) # There is insufficient memory for the Java Runtime Environment to continue 
```

The problem is that **gradle.properties** has maxRAM=140g which is much more than what my computer has. Setting it to a reasonable value fixes the issue. Maybe in another OS, the value gets overriden but in my computer with Ubuntu 16.04 it does not.

**Comment by JustinPihony** [comment]
@bhavyalatha26 I believe that is why Colin created this issue. you have to `export MAXRAM = 10g` or something that fits your system's capabilities

**Comment by bhavyalatha26** [comment]
@JustinPihony the data in the comment was something  that Colin got from a user I guess and he forwarded me on chat as additional reference for the task . I just pasted it here for easy reference.

**Comment by JustinPihony** [comment]
Is there a branch this is waiting on? Otherwise it can be closed I believe.

**Comment by JustinPihony** [comment]
Ping @colinsheppard @bhavyalatha26 ^
