### ISSUE TITLE
physsim_network.xml is written after it is read

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#134]
The NetworkCoordinator creates the physsim_network.xml from R5. It does so at a point where the MATSim scenario is already loaded. So it only becomes consistent after the _second_ run, and it only works at all because physsim_network.xml is checked in.

**Comment by colinsheppard** [comment]
The problem comes from the need for there to be a physsim_network.xml during load, even if R5 has not run for the first time and we therefore do not know what that network looks like. Can we test for the presence of this network when Config is loaded (before MATSim is called) and then if it is not present, create a dummy file?

**Comment by carloscaldas** [comment]
Already solved
