### ISSUE TITLE
If exception happens in RideHailManager constructor, there is no logs

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1341]
I added the line to throw an exception in [RideHailManager.scala](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala#L266). I can see the log right before throwing an exception, but not exception by itself:
![image](https://user-images.githubusercontent.com/5107562/53438503-9db26200-3a32-11e9-8682-3fb109311e51.png)
Logs:
```
01:50:54.511 INFO  beam.sim.RunBeam$ - Starting beam on branch master at commit HEAD.
01:50:54.515 INFO  beam.sim.RunBeam$ - Config [beamville] copied to C:\repos\beam\output\beamville\beamville__2019-02-27_01-50-54\beam.conf.
01:50:54.522 INFO  b.r.r5.DefaultNetworkCoordinator - Initializing router by reading network from: C:\repos\beam\test\input\beamville\r5\network.dat
01:50:56.762 INFO  beam.utils.NetworkHelperImpl - Total number of links is 380 and MaxLinkId is 379.
01:50:56.764 INFO  beam.utils.NetworkHelperImpl - NetworkHelperImpl init executed in 11 ms
01:50:58.102 INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
01:50:58.384 INFO  beam.router.osm.TollCalculator - tollsByLinkId size: 4
01:50:58.384 INFO  beam.router.osm.TollCalculator - tollsByWayId size: 8
01:50:58.410 INFO  b.s.p.DefaultPopulationAdjustment - Modes excluded:
01:50:58.486 INFO  beam.router.r5.R5RoutingWorker - R5RoutingWorker_v2[786275657] `akka://ClusterSystem/user/router/router-worker` is ready
01:50:58.487 INFO  beam.router.r5.R5RoutingWorker - Num of available processors: 16. Will use: 14
01:50:58.690 INFO  beam.sim.BeamMobsim - Starting Iteration
01:50:58.691 INFO  beam.sim.BeamMobsim - Preparing new Iteration (Start)
01:50:58.784 INFO  beam.sim.BeamMobsim - run.start (after GC): 0.03 (GB)
01:50:58.792 INFO  beam.utils.StuckFinder - StuckFinder is ** DISABLED **
01:50:59.234 INFO  hsqldb.db.HSQLDB4AD417742A.ENGINE - dataFileCache open start
Right before throwing an exception
01:50:59.605 INFO  b.a.agents.ridehail.RideHailManager - Right before throwing an exception
```

**Comment by REASY** [comment]
Probably it happens because when we create [rideHailManager](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/sim/BeamMobsim.scala#L103), we use `context` of another actor, instead of `actorSystem.actorOf`. If I use `actorSystem.actorOf`, I'll see:
![image](https://user-images.githubusercontent.com/5107562/53439217-2a115480-3a34-11e9-8956-beffad0626ee.png)

**Comment by REASY** [comment]
@JustinPihony what do you think about such behavior?

**Comment by REASY** [comment]
Long time back I started refactoring [BeamMobsim.scala](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/sim/BeamMobsim.scala#L74) as a part of [PR-537](https://github.com/LBNL-UCB-STI/beam/pull/537), especially that anonymous actor which is responsible for iteration. I believe we should get rid of that anonymous actor and extract it as normal actor with specific type and etc.

**Comment by JustinPihony** [comment]
Sorry, just getting caught up on all my backlog of reviews. The problem I do not believe to be the context being used. The reason you see the output from actorsystem so much quicker is because the Init exception goes straight to the top and nothing is blocking there. Whereas when you are using the actor's context (making it a child) then it is more beholden to ITS own initialization logic and thread. So, the RHM errors, but it won't be reported until the parent is ready. In this case it is a bit of a catch-22 in that we are blocking Await for the RHM to be initialized. If you decrease that timeout duration to something more reasonable then it will work as expected. So, maybe for actor initialization we need to use a different timeout setting, as it shouldn't take too long anyway? Again, a bit of chicken and egg here - and blocking biting us in the butt.

**Comment by REASY** [comment]
Partially solved by adding timeout for RideHailManager to init (https://github.com/LBNL-UCB-STI/beam/pull/1798)
