### ISSUE TITLE
why on production run the missing file error shown, although file present

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1364]
![image](https://user-images.githubusercontent.com/13569531/53607509-a1ee9480-3b84-11e9-9a0a-d7afc9387efd.png)

**Comment by carloscaldas** [comment]
The variable `beam.inputDirectory` should be specified as environment variable or jvm environment variable. If is not specified cannot be resolved. Could you show the command to run the application?

**Comment by wrashid** [comment]
this is not the only path, which uses 
beam.inputDirectory - all others use that as well

**Comment by carloscaldas** [comment]
Fixed by the following PR and commits:

- https://github.com/LBNL-UCB-STI/beam/pull/1468
- https://github.com/LBNL-UCB-STI/beam/commit/702f0925b190e1d88fe90ad68d252044bcf452de
- https://github.com/LBNL-UCB-STI/beam/commit/dbba7b088a80a88915aaa3c28fe5b44b2be27ce7
- https://github.com/LBNL-UCB-STI/beam/commit/5cb5b3db3fbff766032d415607d2759f45505fc7
- https://github.com/LBNL-UCB-STI/beam/commit/ec7c0d335fbfa21405ad32231145c2d4d118ddfc
