### ISSUE TITLE
Don't catch and log unknown messages

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#138]
... but let them fall through instead.

Otherwise we are derailing Akka's exception handling, which means that we have to roll our own one again at other points.

For example, when an agent gets a bad message (wrong parameter, illegal state etc.) and thinks that it is the _sender_'s fault, then, according to Akka, it should reply with a Failure(Throwable) message, which produces desired default behavior.

However, if we _swallow_ that message at the receiving end, this doesn't work.

**Comment by sfwatergit** [comment]
Right now we let the agents Goto an error state and swallow errors for a very specific reason... They need to send completion notices back to the scheduler. 

Of course, this should not be happening nearly as often; however, there will remain a continuing need to do this as a result complex  situations  having to do with reserving rides on multi hope transit, reaching a full bus and then needing to cancel replan part way through. Until this scenario is dealt with (at least) there will need to be some agents that must stay in error for a short period of time before, perhaps, ultimately being stopped. Perhaps, an alternative would  be  a custom catch all mailbox implementation that returns completion notices (rather than passing to dead letters and hanging the system). I don't think we should permit the whole system to hang on most agent runtime errors (or at least make this configurable). Bugs are inevitable, so a 100% bug free goal may lead to a long game of whack mole that may introduce more kludges for edge cases than thoughtful refactoring to simplify protocols.  

Current policy is also not to stop errored agents explicitly. Should we rectify this?

**Comment by michaz** [comment]
I'm fine with the explicit error state (although it would be nice if it would automatically be sent there on exceptions from within the agent, so that you can throw insted of call an error method).

What I mean is only the "unknown message -> stay silent" behavior which is in almost every actor.

**Comment by michaz** [comment]
Also, the system shouldn't _hang_ when an actor (e.g. the router) _actually_ dies (despite explicit error handling for agents). It should crash.
Otherwise, people will think actors aren't _allowed_ to die, under any circumstances (because the system shouldn't hang), and code around that, and suddenly there will be catch-alls all over again.

**Comment by michaz** [comment]
Full example: Suppose there's and exception during a routing request. Either a) from the problem domain (no route found), b) from the infrastructure (don't know, database unavailable, or something), or c) unexpected (null pointer) or d) illegal request.

When I throw an Exception from the router, the router dies, and Akka restarts it and goes on. Does that help, in our use case? Only maybe in situation b), if the router were something which would benefit from being restarted, and only if we would use some Akka-functionality to retry the message, otherwise the agent wouldn't get an answer.

In case c) and d), I just realize I shouldn't let the _router_ crash, because that doesn't help anyone. I should let the _agent_ crash. Assuming that the agent would somehow intercept its own crash and move to the error state to remove itself from the simulation. (Applies also to the agent scheduler vs. an agent who sends an illegal trigger).

In Akka (I just read that up), you do that by _replying with an exception-message, Failure(e). Advantage over self-built error messages: stack trace is recorded.

**Comment by michaz** [comment]
... but _that_ doesn't work, because Failure(e) is swallowed by all our agents as an unknown message, instead of, for instance, being received and sending the agent to the error state. Which is I think what you had in mind, and I support that!

**Comment by michaz** [comment]
(And I don't think that's intentional. All our actors swallow all unknown messages, I think that's the pattern. Not swallowing Failures in particular.)

**Comment by sfwatergit** [comment]
There is some documentation on Supervision:
https://doc.akka.io/docs/akka/2.5.4/scala/general/supervision.html

and Fault Tolerance:
https://doc.akka.io/docs/akka/current/scala/fault-tolerance.html

is this what you have in mind?

**Comment by colinsheppard** [comment]
I'm not sure I agree that generic failure messages are always better than custom. Yes a stack trace is helpful, but doesn't always give you everything you need, which is where custom messages are useful.

That said, we can probably get the best of both. We can remove the catch-all unknown message handling from all of our actors and replace with handling of Failure messages where needed. In particular, the BeamAgent trait would be a natural location.

Then we can keep some degree of custom messaging when useful... i.e. returning a RoutingResult with 0 itineraries (instead of crashing) is useful because some agents can still be productive (e.g. RideHailManager can still function).
