### ISSUE TITLE
investigate: high car travelTime pathTraversal

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1575]
It has been observed on production run, that some car pathTraversals take much longer on the freeFlow network (iteraiton 0) compared to google maps.

-> why? E.g. look at routes

**Comment by REASY** [comment]
It's due to the usage of warm-mode. Seems like the data which we use for warm-start (https://s3.us-east-2.amazonaws.com/beam-outputs/sfbay-smart-base__2019-04-01_22-41-19_warmstart.zi) contains odd data. Routing request 
```json
{
  "originUTM" : {
    "x" : "600027.8096093484",
    "y" : "4244289.332185422"
  },
  "destinationUTM" : {
    "x" : "553536.034318063",
    "y" : "4180185.6732567726"
  },
  "departureTime" : 19792,
  "transitModes" : [
  ],
  "streetVehicles" : [
    {
      "id" : "rideHailVehicle-5526408",
      "vehicleTypeId" : "RH_ConventionalGas_Low",
      "locationUTM" : {
        "loc" : {
          "x" : "600027.8096093484",
          "y" : "4244289.332185422"
        },
        "time" : 19792
      },
      "mode" : {
        "CAR" : {
          
        }
      },
      "asDriver" : false
    }
  ],
  "attributesOfIndividual" : null,
  "streetVehiclesUseIntermodalUse" : {
    "Access" : {
      
    }
  },
  "requestId" : 434377
}
```
Returns the leg with duration equals to 26499 seconds, when warm start is enabled. In case of disabled warm-start, the duration is around 5500 seconds.
