### ISSUE TITLE
update warmstart

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1790]
-> e.g. include sampled vehicles, including personal CAVs
-> what else needs to be loaded?

**Comment by JustinPihony** [comment]
@wrashid After talking to Colin and Carlos I believe this work is a bit duplicative to the work being done for reading and writing csv. i.e. - https://github.com/LBNL-UCB-STI/beam/pull/1839

That said, it was discussed that given the new procedural, on the fly nature, we should clean the code such that it follows clear stages:

* Read any data available (this includes warmstart and root files such as vehicles or households)
* Fill in the rest of the data
* Write out the final data to the output directory (for later reading back in maybe)
* Execute the simulation

If that resonates with you then I'm proposing that we complete the above mentioned PR and create a new issue for the above reorganization. Along with that, create two new issues to migrate ridehailfleet data and urbansim data such that they are output to the root, rather than per iteration - as they are redundant beyond the initial load. Of course those additional two items need verified, but Colin seemed confident that they should be movable to root.

**Comment by wrashid** [comment]
@JustinPihony yes, the idea is that we would use the readers provided by @carloscaldas for this task. Plan makes sense. Please coordinate with @carloscaldas and let us discuss if any open questions.

**Comment by JustinPihony** [comment]
Closing this issue in favor of the work @carloscaldas has already done and what is to be done via https://github.com/LBNL-UCB-STI/beam/issues/1853
