### ISSUE TITLE
repair lots of ignored tests

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#186]

**Comment by fdariasm** [comment]
Currently MultinomialCustomConfigSpec, RideHailPriceSpec and RideHailCostPerMileSpec are ignored.

**Comment by fdariasm** [comment]
I think this is done by @michaz. Please confirm and close issue if that's the case

**Comment by michaz** [comment]
I successfully re-enabled _some_ tests. Multinomial.. seems to be on again, RideHail* not.
Meanwhile, many more tests were *dis*abled.

Getting the tests enabled again, and maybe checking on the way if they actually (still) test anything, remains something we need to do together..

**Comment by michaz** [comment]
This means we can and should also delete tests which are too unspecific, which can never fail, which test a class against itself etc.

**Comment by michaz** [comment]
See https://github.com/LBNL-UCB-STI/beam/issues/928

**Comment by fdariasm** [comment]
ok @michaz, I was working on EventsFileSpec which I noticed you fixed most of it and it was the only one I detected as failing last time I checked. I see now the list of failing/ignored tests is longer, these are some of them that I have some familiarity with:

- RideHailPriceSpec: Running beam with modeChoice ModeChoiceMultinomialLogit and increasing rideHailPrice value.
- RideHailBufferedRidesSpec.
- RideHailCostPerMileSpec.
- ZonalParkingManagerSpec.
- ModeChoiceSpec.
- ParkingSpec. -> This is fixed in another branch
- RideHailNumDriversSpec

Will be checking those this afternoon.
