### ISSUE TITLE
Remove default-energy-primary.csv from all vehicleTypes.csv files

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1988]
Across all input data, including in all production branches, please find all instances of a vehicleTypes.csv file (and the variations on that same file) and remove any reference to 

"default-energy-primary.csv"

or 

"default-energy-secondary.csv"

in these files. We don't need to specify a file path for the columns "primaryVehicleEnergyFile" and "secondaryVehicleEnergyFile" so these can be left blank instead of referring to some default energy file.

If there is a value that refers to an actual file (e.g. "/AllAboutMe_longTerm_highTech/conv-car-gas.csv.gz") then definitely leave that

**Comment by JustinPihony** [comment]
The biggest difference here is that if there is no file specified then it will use the fallback calculation, which is a static number. Whereas the default allows for a more dynamic calculation based on grades, lanes, speed, and such. Granted the default is more geared towards a specific zone, so maybe that's why we want to go with the static default versus dynamic default. Alternatively, we could have a single location where we specify the default file locations. But I guess that would just about negate the static fallback entirely. More food for thought than anything else.
