### ISSUE TITLE
resolve "java.lang.RuntimeException: Cannot create a CDF based on a PDF without any non-zero probability density"

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#202]
exception thrown multiple times in application-sfbay base run.

**Comment by colinsheppard** [comment]
This exception occurs when a logit model is either evaluated with zero alternatives or the utility of every alternative is -INFINITY, leading to a malformed probability distribution that is all zeros.

For now, I will add some more informative error handling.  

But the real problem is diagnosing why these agents have no alternatives or none with non-infinite utility.
