### ISSUE TITLE
discuss if to continue using link stats or replace with different code

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#205]

**Comment by michaz** [comment]
Hmm, if you don't like it, I'd just write a new one. This is really just a report, it's nothing particularly clever or tightly integrated.
_Given_ that I want to write a new one, however, I would probably start from scratch and write it exactly how I want it, rather than starting with the MATSim one and changing it in a few places. Just my opinion though.

**Comment by colinsheppard** [comment]
Agreed.. and for the record, currently it has the following problems:

-- wide format, makes parsing and manipulating a chore, long format much preferred (e.g. "from,to,hour,length,freespeed,capacity,stat.type,volume,traveltime" where stat.type can be max,min,avg)

-- stops at 24, so with our plans that go from 6-30, we miss out on link stats after midnight
