### ISSUE TITLE
To Implement the ChargingNetworkManager

### ISSUE THREAD

**Issue by haitamlaarabi** [LBNL-UCB-STI/beam#2845]
Implement the ChargingNetworkManager that undertakes a list of tasks every X time interval:
1) Estimate the required power in the next Y time interval > X time interval
2) if BEAM connected to grid: Communicate via HELICS/BeamFederate the estimated power and wait for Physical Bounds from the grid (min, max Power and price)
3) Otherwise: Use default Physical Bounds: Min = Max = RequiredPower & price = 0
4) Update PricingAndPhysicalBounds in the class SitePowerManager
5) Call getChargingPlanPerVehicle in SitePowerManager, which returns a map of vehicles with amount of energyInJoules to charge the corresponding vehicle
6) Loop over vehicles, and create a copy of the vehicle as a dummy vehicle and add energyInJoules.
7) If vehicle is fully charged before end of the time interval X, then delete dummy vehicle from memory (for now, don't send message protocol to the Driver via the scheduler)

![Screen Shot 2020-07-15 at 11 08 39 AM](https://user-images.githubusercontent.com/10712736/87580163-e8fefc00-c68b-11ea-83c2-692af4002307.png)

**Comment by jctim** [comment]
### Run without ChargingManager enabled:
![stopwatch](https://user-images.githubusercontent.com/427642/90215843-44dcb200-ddfd-11ea-93d0-275fe5c843fb.png)

### Runs with ChargingManager enabled with delay=0s before power flow response:
![stopwatch](https://user-images.githubusercontent.com/427642/90215900-6b9ae880-ddfd-11ea-9f50-32b41e91739f.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90215911-72c1f680-ddfd-11ea-89ea-3fe8bbd624a5.png)

### Runs with ChargingManager enabled with delay=0.01s before power flow response:
![stopwatch](https://user-images.githubusercontent.com/427642/90215932-84a39980-ddfd-11ea-9e6d-98ee0e33503e.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90215951-8ec59800-ddfd-11ea-90e8-634d1912e256.png)

### Runs with ChargingManager enabled with delay=0.1s before power flow response:
![stopwatch](https://user-images.githubusercontent.com/427642/90215981-a1d86800-ddfd-11ea-8a43-fb8abbd32cef.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90215989-a69d1c00-ddfd-11ea-90dd-43ffbcadd62d.png)

### Run with ChargingManager enabled with delay=1s before power flow response:
![stopwatch](https://user-images.githubusercontent.com/427642/90216021-bcaadc80-ddfd-11ea-9f9a-4b6c8dfbe2ef.png)

### Run with ChargingManager enabled with delay=rand(0, 0.1s) before power flow response:
![stopwatch](https://user-images.githubusercontent.com/427642/90216060-d64c2400-ddfd-11ea-8926-878e15e7cea6.png)

### Run with ChargingManager enabled with delay=rand(0, 1s) before power flow response:
![stopwatch](https://user-images.githubusercontent.com/427642/90216079-e19f4f80-ddfd-11ea-893b-e4138b53a3ea.png)

**Comment by jctim** [comment]
@haitamlaarabi I made changes in the code and configuration as required.
And what I got after (each case is run twice):

### 1. ChargingNetworkManager is configured to not be connected to grid
```
beam.agentsim.chargingNetworkManager.gridConnectionEnabled = "false"
```
#### Logs examples
```
23:36:25.466 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: false
23:36:25.467 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@59033fad)

23:36:49.387 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: false
23:36:49.387 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@3d09fc16)

23:37:04.328 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: false
23:37:04.328 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@5ce81043)
```
#### Stopwatch graphs
![stopwatch](https://user-images.githubusercontent.com/427642/90322256-99457600-df52-11ea-9ff7-e14c0bd0a687.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90322260-9fd3ed80-df52-11ea-8528-290ccfcd262d.png)

### 2. ChargingNetworkManager is configured to be connected to grid but broker is not running
```
beam.agentsim.chargingNetworkManager.gridConnectionEnabled = "true"
+
no python script running
```
#### Logs examples
```
23:39:46.674 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: true
23:40:13.406 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager is connected to grid: false
23:40:13.409 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@d43d3d4)

23:40:37.961 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: true
23:41:01.982 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager is connected to grid: false
23:41:01.982 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@58934314)

23:41:18.673 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: true
23:41:42.730 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager is connected to grid: false
23:41:42.730 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@48019643)
```
##### Notes
Time spent by BeamFederate to realize there is no broker is about **24 sec** (27 sec for first iteration, probably because of `HelicsLoader.load()`)
#### Stopwatch graphs
![stopwatch](https://user-images.githubusercontent.com/427642/90322354-841d1700-df53-11ea-81b7-96c685552b9f.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90322380-91d29c80-df53-11ea-8011-2952ed5ae0c3.png)

### 3. ChargingNetworkManager is configured to be connected to grid and broker is running with delay=0s
```
beam.agentsim.chargingNetworkManager.gridConnectionEnabled = "true"
+
python3 helics/GridBroker.py
line66:     time_sleep = 0
```
#### Logs examples
```
23:45:21.812 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: true
23:45:24.810 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager is connected to grid: true
23:45:24.818 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@32eb0e46)

23:45:54.794 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: true
23:45:54.901 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager is connected to grid: true
23:45:54.902 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@54860b9c)

23:46:14.999 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager should be connected to grid: true
23:46:15.166 INFO  b.a.i.ChargingNetworkManager - ChargingNetworkManager is connected to grid: true
23:46:15.167 DEBUG b.a.i.ChargingNetworkManager - started (beam.agentsim.infrastructure.ChargingNetworkManager@5a192b33)
```
##### Notes
Time spent by BeamFederate to connect to the broker is less then **200 ms** (about 3 sec for first iteration, probably because of `HelicsLoader.load()`)
#### Stopwatch graphs
![stopwatch](https://user-images.githubusercontent.com/427642/90322438-5a182480-df54-11ea-8b3c-36e97024aacc.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90322441-5e444200-df54-11ea-80ef-17339e635424.png)

### 4. ChargingNetworkManager is configured to be connected to grid and broker is running with delay=0.01s
```
beam.agentsim.chargingNetworkManager.gridConnectionEnabled = "true"
+
python3 helics/GridBroker.py
line66:     time_sleep = 0.01
```
#### Logs examples
_(similar to previous)_
##### Notes
_(similar to previous)_
#### Stopwatch graphs
![stopwatch](https://user-images.githubusercontent.com/427642/90322452-83d14b80-df54-11ea-8ce2-9067f8111643.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90322453-8633a580-df54-11ea-92bc-007fa85095fb.png)

### 5. ChargingNetworkManager is configured to be connected to grid and broker is running with delay=0.1s
```
beam.agentsim.chargingNetworkManager.gridConnectionEnabled = "true"
+
python3 helics/GridBroker.py
line66:     time_sleep = 0.1
```
#### Logs examples
_(similar to previous)_
##### Notes
_(similar to previous)_
#### Stopwatch graphs
![stopwatch](https://user-images.githubusercontent.com/427642/90322456-9186d100-df54-11ea-9d53-2ee95ca9e214.png)
![stopwatch](https://user-images.githubusercontent.com/427642/90322459-95b2ee80-df54-11ea-9600-2a8fb4105765.png)

### 6. ChargingNetworkManager is configured to be connected to grid and broker is running with delay=1s
```
beam.agentsim.chargingNetworkManager.gridConnectionEnabled = "true"
+
python3 helics/GridBroker.py
line66:     time_sleep = 1
```
#### Logs examples
_(similar to previous)_
##### Notes
_(similar to previous)_
#### Stopwatch graphs
_TO BE ADDED_
