### ISSUE TITLE
Hao2018CaccRoadCapacityAdjustmentFunction: Why it take so long to write an empty image?

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3033]
Is there a lot of data points? Can it be optimized? If no we need to introduce new flag to control it.
![image](https://user-images.githubusercontent.com/5107562/95612209-39b8a200-0a8d-11eb-8625-d4577e8f569e.png)

https://github.com/LBNL-UCB-STI/beam/issues/3024#issuecomment-706260004

**Comment by dimaopen** [comment]
This physsim iteration produced ~1e9 physsim events. Each time a vehicle enters or leaves road a new data entry is added to the collection which is used for generating a scatter plot. During the scatter plot generation no optimization happens on data and all the affine transformation happens for each data entry. This is a pretty heavy operation. This is why it takes so long.
I think the performance may be optimized if we use HashSetValuedHashMap instead of ArrayListValuedHashMap as a collection that holds data entries.
