### ISSUE TITLE
Performance: PARBPR better CPU utilization

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3045]
![image](https://user-images.githubusercontent.com/5107562/96023322-71a05a80-0e7c-11eb-8be5-ff66becc3cb4.png)
Run: https://github.com/LBNL-UCB-STI/beam/issues/3024#issuecomment-707714458
@dimaopen comment:
> I think that the bottleneck is the coordinator thread which accepts the events from the workers and pass them to the EventManger. The event handlers processing events, which takes time. AFAIR these events should go sequentially.
I think that one of the solution would be to use some intermediate event queue. This would consume memory. And the event consumption may last after the physsim finishes.

**Comment by dimaopen** [comment]
The approach with an intermediate event queue didn't work because the next iteration needs the results of the handlers. Some of handlers that produces results that are not required by the next iteration are quick (i.e. PhysSimEventWriter).

Another solution is to create a special physsim event manager that would handle each event handler on its own thread. Because we have multiple handlers that process events roughly at the same speed this should give us some performance improvement.

**Comment by dimaopen** [comment]
A performance test is taken on on Austin-prod-200k.
Old JDEQ sim (cacc enabled) 1242914 ms with writing events to disk
                                                 639434 ms no writing
Old PARBPR (cacc disabled) 982257 ms with writing events to disk

Par JDEQ sim (cacc disabled) 411868 ms with writing events to disk
                                                 383819 ms no wrting
