### ISSUE TITLE
Test out beam.agentsim.agents.vehicles.sharedFleets

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3066]
- First task to explore effort: how to model multi-modal trips with sharedFleets and transit.
- how to create mode choice model for sharedFleets?
- how difficult to include stations/hubs for sharedfleets (instead of free floating, as at the moment).
- look at scenario: change price, no cars at all, use sharedFleets as access and egress mode to transit.

Can we also check how the vehicle repositioning is working (a vehicle can change its position in auto mode)? Does it work?

**Comment by dimaopen** [comment]
1. We can enable a shared fleet so that shared cars are available to the people. A person would choose between car alternative that corresponds to the shared car provided by the shared fleet manager and other alternatives including transit. This is an example of configuration:
`beam.agentsim.agents.vehicles.sharedFleets = [
    {
      name = "my-fixed-non-reserving-fleet"
      managerType = "fixed-non-reserving"
      #@optional
      fixed-non-reserving {
        vehicleTypeId = "sharedCar",
        maxWalkingDistance = 500
      }
      #@optional
      reposition {
        name = "my-reposition-algorithm"
        repositionTimeBin = 3600,
        statTimeBin = 300,
        #@optional
        min-availability-undersupply-algorithm {
          matchLimit = 99999
        }
      }
    }
  ]`

2. Shared cars are chosen among other alternatives. It uses the same car intercept as regular cars do. It can be influenced by the car type parameters (monetaryCostPerMeter,monetaryCostPerSecond). See vehicleTypes.csv.

**Comment by dimaopen** [comment]
3. Thought on implementation hubs.

- MobilityStatusResponse includes coordinates of vehicles and possible parking hubs if applicable
- Create a new class RoutingRequestWithIntermediatePoints which extends the regular RoutingRequest and also has 2 shared fleet parking points (origin, destination).
- During Mode Choice when we have shared vehicles available then we send this new RoutingRequestWithIntermediatePoints to the Router. When the router gets this request it makes 3 requests to R5:
1. WALK: origin -> shared hub 1
2. CAR: shared hub 1 -> shared hub 2
3. WALK: shared hub 2 -> destination
The results are combined into itineraries.
- We also need to claim the shared car in the middle of our trip. Hopefully, the same code that does it now would work: https://github.com/LBNL-UCB-STI/beam/blob/de161ee38430b4a2dcb86f15fd303c0385240403/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L765

**Comment by dimaopen** [comment]
After some research, I found that 1. WALK: origin -> shared hub 1 is not needed because R5Wrapper takes care of it.

Instead of 3. WALK: shared hub 2 -> destination we could reuse Parking Behavior of the agents. The parking manager could ask for a parking hub from the corresponding shared fleet manager. In this case we need to check that theare is a parking hub close to the destination before provide a shared car to a person. And if we need to model limited parking space on these hubs then the person can park too far away from the destination (on a free parking hub)

**Comment by dimaopen** [comment]
This is another way how we could implement hub/stations.
We asks for a parking from the vehicle manager. And the vehicle manager returns the nearest hub or passes the ParkingInquiry to the Parking manager.
1. We need to ensure that when we are in the ChoseMode then we doesn't calculate parking cost for the shared vehicles. I think at that state the shared vehicles are just tokens (not actual vehicles) and in this case we can consider the parking cost equals to zero.
2. We need to enable parking behavior for shared bikes in order to get hubs working for bikes. I have not understood how to do this yet.
![ProtocolTravelingSharedCar](https://user-images.githubusercontent.com/1764256/99089155-ff877680-25dd-11eb-8444-20a8b33f1eb8.png)

**Comment by dimaopen** [comment]
I think that to implement shared vehicle hubs we could have configured a dictionary VehicleType -> ParkingManger, not configured types goes to the default Parking Manger. Then shared vehicles goes to preconfigured Parking Manager where we could set up a many hubs as we want.
