### ISSUE TITLE
Teleportation: Create a way of teleporting actors from origin to destination

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3106]
This should not affect phys simulation in any way.
This teleportation should happen between departure and arrival events. 
The teleportation should use some new mod, for example - 'teleportSharedCar'.
This mode should be taken from transportation plans ???

**Comment by zneedell** [comment]
> This mode should be taken from transportation plans ???

Yeah, I think the ideal outcome could be when we get an input plan that has a mode like 'passenger in shared car,' and then we know to teleport them and throw some pathTraversalEvent to acknowledge the teleportation, but not bother with entering/exiting vehicles or physsim.

**Comment by REASY** [comment]
ActivitySim will provide modes, wider than our modes, like HOV2 (driving in a car with two people in it). But the input doesn't say who is a driver and who is a passenger. In order to model this we can approximate it by assigning to the person whether they are passenger or driver with 50% probability. Might be done in ModeChoice or as preprocessing step. 

Toss a coin and if it shows that this is a driver, then this person can use household car and drive (but number of people in PTE is 2). If it was a passenger, we just teleport this person to destination. Make sure there are consistency of the events. If it is needed we can estimate travel time and delay arrival.

For HOV3 the probability of being a driver is 1/3, so if it is a driver then 3 people will be driving (PTE will have 3 people). The chance of teleportation is 1 - 1/3 = 2/3.

**Comment by nikolayilyin** [comment]
If a person uses HOV2/3 mode and doesn't have a car in his household, then the car will be created out of thin air with a type randomly taken from existing in simulation car types.

**Comment by zneedell** [comment]
Hmm, yeah that's a tough question. I think the first pass solution could be just to ignore how many cars the household has available and if they don't have a car they just need to replan, but if that happens often that could be a problem.

I'm wondering if there's a more elegant solution that has these people more likely to be passengers and people with extra cars more likely to be drivers, but I can't think of a good way of making it work. Let's discuss today.

**Comment by nikolayilyin** [comment]
As discussed - the solution with creating cars from thin air is not the best. 
The solution with preprocessing of the plans is the way to go.
The solution is the follow: 
1. preprocess plans and replace each hov2/3 with either car2/3 or hov2/3teleportation based on car availability and randomness,
2. do a sanity check to verify that at any given moment of time a person has available car at household, i.e. there should not be two persons using car at the trip from household at the same time with only one car in household at the beginning of both trips.

**Comment by nikolayilyin** [comment]
ActivitySim input contains joined trips as well as HOV2|3 modes.
Each joined trip contains one person that has plans\tours\e.t.c associated with joined trip and a group of additional persons that does not have plans\tours associated with joined trip, these additional persons are just the additional number of passengers which should be kept for the duration of the joined trip (at least for PathTraversal events)

**Comment by nikolayilyin** [comment]
tests:
1. check if activities happen at the expected location with the expected duration
2. check modes from events
3. check modes from realizedModeChoice file
4. check the number of physical cars
5. check the number of passengers in HOV cars

**Comment by nikolayilyin** [comment]
Currently teleportation works for beamville during iteration 0, but after iteration 0 actors do not use teleportation.
Investigation required.

Also for Austin runs teleportation does not works even at iteration 0.
Investigation required,

**Comment by nikolayilyin** [comment]
it is implemented and merged into develop long time ago
