### ISSUE TITLE
Remove deprecated config parameters

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3117]
Beam writes in the log the following:
```
**  
** Found the following deprecated parameters, you can safely remove them from your config file:
**  
**  beam.agentsim.agents.parking.mulitnomialLogit.params.distance_multiplier
**  beam.agentsim.agents.parking.mulitnomialLogit.params.installed_capacity_multiplier
**  beam.agentsim.agents.parking.mulitnomialLogit.params.parking_costs_price_multiplier
**  beam.agentsim.agents.rideHail.initialization.procedural.numDriversAsFractionOfPopulation
**  beam.outputs.generalizedLinkStats.interval
**  beam.outputs.writeSkimsInterval
```

Let us clean-up our configs. Also are those the only deprecated params?

**Comment by HoneyTauOverTwo** [comment]
Running Beamville scenario currently now outputs more deprecated parameters (most of the originally reported are missing):

```
** Found the following deprecated parameters, you can safely remove them from your config file:
**  
**  beam.agentsim.agents.rideHail.refuelThresholdInMeters
**  beam.agentsim.startTime
**  beam.cosim.helics.federateName
**  beam.cosim.helics.timeStep
**  beam.outputs.writeLinkTraversalInterval
**  beam.physsim.writeMATSimNetwork
**  beam.replanning.cleanNonCarModesInIteration
**  beam.router.skim.collectFullCarSkimsInterval
**  beam.router.skim.h3Resolution
**  beam.router.skim.origin_destination_skimmer.fileBaseName
**  beam.router.skim.origin_destination_skimmer.name
**  beam.router.skim.origin_destination_skimmer.writeAllModeSkimsForPeakNonPeakPeriodsInterval
**  beam.router.skim.origin_destination_skimmer.writeFullSkimsInterval
**  beam.router.skim.travel-time-skimmer.fileBaseName
**  beam.router.skim.travel-time-skimmer.name
**  beam.routing.r5.osmFile
```

It has a duplicated parameter but with two different values, I am pretty sure the first one is being used, but they were left as is (should I remove the second?):

```
beam.outputs.baseOutputDirectory = ${PWD}"/output/sf-light"
beam.outputs.baseOutputDirectory = ${?BEAM_OUTPUT}
```

running beamville/beam-urbansimv2 did not output any other additional deprecated parameter. There were lots of duplicated parameters.

running network-relaxation-scenario did not output any other additional deprecated parameter.

running sf-light urbansim-1k scenario had the additional parameter as deprecated: ``beam.beamskimmer.writeObservedSkimsInterval``. Also, it had the following parameters duplicated:

```
**  beam.agentsim.agents.rideHail.surgePricing.minimumSurgeLevel
**  beam.agentsim.agents.rideHail.surgePricing.priceAdjustmentStrategy
**  beam.agentsim.agents.rideHail.surgePricing.surgeLevelAdaptionStep
```

sf-light urbansim-10k yielded the additional deprecated parameter: ``beam.outputs.writeSkimsInterval``

sf-light urbansim-250k yielded: ``beam.agentsim.agents.rideHail.initialization.procedural.numDriversAsFractionOfPopulation``

sf-light urbansim-100k yielded ``beam.agentsim.numAgents``.

Contrary to the previous scenarios, urbansim-10k, 100k and 250k, after being edited, were ran only until the simulation started, which I assume was enough to discard the possibility of configuration errors.

urbansim-25k failed with ``ERROR o.m.c.controler.AbstractController - Mobsim did not complete normally! afterMobsimListeners will be called anyway.`` even with the original config.

Whent trying to run the scenarios ``test/input/texas/austin...`` beam exits with errors due to missing files, for that reason I did not analyze those.
