### ISSUE TITLE
RunBeam with test inputs

### ISSUE THREAD

**Issue by Hotlineblinn** [LBNL-UCB-STI/beam#3118]
Hi guys,
I am currently learning how to run beam with v0.7.0 base , no coding background at all.
I managed to run beam with the example inputs (beamville, sflight etc.) thanks to the help of beam team.

However, now that I am using my own inputs this is what I see.
Could anyone kindly help out this newbie?
Thank you in advance.

![캡처](https://user-images.githubusercontent.com/76731360/108675002-862ae880-7529-11eb-9e5b-e8d3264b5fb3.PNG)

**Comment by nikolayilyin** [comment]
Hi Hotlineblinn, it is impossible to help you based on this picture because this is a generic error message which is telling that something went wrong, but not telling what exactly went wrong.

Try to run BEAM with example input and then move to your input changing one thing at a time, this way you will know what change in input data leads to problems.
