### ISSUE TITLE
NERSC: running BEAM, calculating skims

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3198]
We have access to nersc (documentation - https://docs.nersc.gov)
We need to develop a way to do the following things:

- [ ] run BEAM
- [ ] deploy BEAM on nersc using gradle command, i.e. without running it there manually
~~generate skims in parallel on multiple nodes (probably manually)~~ Moved to #3208
- [ ] write a documentation of how to do it

There is a Jupyter lab on NERSC, so, it might be possible to use Jupyter to run\deploy BEAM and\or to generate skims.

Could be useful: https://github.com/LBNL-UCB-STI/beam/issues/3144

**Comment by dimaopen** [comment]
Using beam images that is referenced to in #3144 I was able to run sf-light-1k scenario on a single node. The BEAM output got to the user's home dir (Global Home NERSC storage). NERSC documentation says that the program input/output should be stored at Cori scratch storage (purged).

**Comment by nikolayilyin** [comment]
in case of using deploy command to run BEAM on nersc we need to create some kind of protection for private keys used to access nersc

**Comment by dimaopen** [comment]
In order to automate running BEAM on NERSC one needs to take into account the following:

1. BEAM needs to be run within a docker container that is available at a docker repository (i.e docker hub).
2. NERSC infrastructure has multiple storage systems that serve different purposes. See https://docs.nersc.gov/filesystems/.
3. To authenticate to NERSC infrastructure one needs to use their password + One-time password generated by the authenticator app. One can create a short-term (24 hours) ssh key using sshproxy tool developed by NERSC. NERSC can also create for us a long-term SSH key after evaluating our request.


In order to run BEAM, we could create a docker image with the tools that are sufficient to run BEAM (git, git-lfs, java-8, miniconda probably).

Then the workflow is the following:

1. User creates a temporary ssh key for NERSC.
2. User issues a Gradle command to deploy to NERSC.
3. Gradle copies run_beam.sh script to a NERSC machine and executes it in daemon mode so that the ssh session could be closed without script interruption. A solution is here https://askubuntu.com/questions/349262/run-a-nohup-command-over-ssh-then-disconnect. Also, AWS credentials, git branch/commit, config path environment variables should be set at this time on the NERSC machine. We could probably use Gradle ssh plugin for that (https://gradle-ssh-plugin.github.io/)
4. The script mounts a tmp directory on scratch file system as a volume of the docker container and starts the container. Something lik that:
`shifter --image=beammodel/beam:0.8.6.4-nersc -v $SCRATCH/tmp_folder_xyz123:/beam_app /app/entrypoint.sh`
5. Container's entrypoint script downloads the required git commit and starts BEAM
6. After BEAM finishes run_beam.sh script uploads the results to the AWS S3 storage.

**Comment by dimaopen** [comment]
Test!
