### ISSUE TITLE
Analyze T-SCORE team BEAM log. 

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3309]
We need to understand what went wrong with big BEAM simulation that T-SCORE team doing:
1. maybe something wrong with scenario
2. maybe we have bugs in the code
3. maybe there are some improvement we might made in order to avoid these problems

**Comment by nikolayilyin** [comment]
the log file from died simulation:
[slurm-43341457.out.gz](https://github.com/LBNL-UCB-STI/beam/files/7184157/slurm-43341457.out.gz)

**Comment by heyrutvik** [comment]
It looks like [the ridehail manager is stuck](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala#L261), and the scheduler is waiting for its response. Since, [awaitingResponse](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala#L135) is not cleared, simulation doesn't progress. And the main gets timed out.

Important logs:
```
nowInSeconds=71828
	awaitingResponse.size=5
	triggerQueue.size=62799
	triggerQueue.head=Some(ScheduledTrigger(TriggerWithId(ActivityEndTrigger(71829),1332561),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/population/200673/567758#-1248982667],0))
	awaitingResponse.head=Set(ScheduledTrigger(TriggerWithId(BufferedRideHailRequestsTrigger(71800),8261565),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager#1000167981],0))

16:16:27.374 INFO  b.a.scheduler.BeamAgentScheduler - awaitingResponse:ScheduledTrigger(TriggerWithId(BufferedRideHailRequestsTrigger(71800),8261565),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager#1000167981],0)
16:16:27.374 INFO  b.a.scheduler.BeamAgentScheduler - awaitingResponse:ScheduledTrigger(TriggerWithId(EndLegTrigger(71805),8261643),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager/rideHailAgent-rideHailVehicle-1-1-7#1390054430],0)
16:16:27.374 INFO  b.a.scheduler.BeamAgentScheduler - awaitingResponse:ScheduledTrigger(TriggerWithId(EndLegTrigger(71813),8261641),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager/rideHailAgent-rideHailVehicle-1-1-1#1077376766],0)
16:16:27.374 INFO  b.a.scheduler.BeamAgentScheduler - awaitingResponse:ScheduledTrigger(TriggerWithId(EndLegTrigger(71815),8185750),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/population/17959/1162304#-190977829],0)
16:16:27.374 INFO  b.a.scheduler.BeamAgentScheduler - awaitingResponse:ScheduledTrigger(TriggerWithId(EndLegTrigger(71825),8261644),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager/rideHailAgent-rideHailVehicle-1-1-5#508225960],0)

nowInSeconds=71828
	awaitingResponse.size=1
	triggerQueue.size=62799
	triggerQueue.head=Some(ScheduledTrigger(TriggerWithId(ActivityEndTrigger(71829),1332561),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/population/200673/567758#-1248982667],0))
	awaitingResponse.head=Set(ScheduledTrigger(TriggerWithId(BufferedRideHailRequestsTrigger(71800),8261565),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager#1000167981],0))
```

Facts (correct me If I'm wrong):
- we send completion notice [when an agent dies](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala#L352).
- we step a simulation forward only if `awaitingResponse` is empty. (hence no increment in 'nowInSeconds' too?)

Reasoning:
- When we arrive at 71828 in seconds, we are waiting for 5 completion messages. We send completion notices for four agents when they die, and the count of `awaitingResponse` become 1.
- Now, we waiting a completion notice from the ridehail manager (for `BufferedRideHailRequestsTrigger` specifically). But it seem like it's stuck and couldn't fulfil the request. Hence, no progress in simulation, and iteration times out.

I'm not sure if it's possible to figure out from the logs what causes the stuckness of ridehail manager. If there are any hints then please let me know, I'll try to come up with possible reasons.

cc @nikolayilyin @zneedell @JustinPihony

**Comment by nikolayilyin** [comment]
We are postponing work on that issue up to the moment we get updated log from T-SCORE team

**Comment by JustinPihony** [comment]
As far as I can tell it looks like it started to `Interrupt` through `startWaveOfRepositioningOrBatchedReservationRequests` (from the `BufferedRideHailRequestsTrigger`) but never completed - an `Interrupt` for the stuck Id was sent to `ErrorListener` instead of the `Agent` - This is supposed to recover via `InterruptedWhileOffline` but seems it did not. I'll dig in more on that soon.

**Comment by JustinPihony** [comment]
Aha! A bug in ErrorListener -interestingly it has been there [since its addition](https://github.com/LBNL-UCB-STI/beam/commit/71376604751384c78a2e8b18db92f7f9c2508fe3). This does not necessarily answer why an Agent was offline, but if fixed it should at least let it heal as it was intended.

**Comment by JustinPihony** [comment]
https://github.com/LBNL-UCB-STI/beam/issues/3316 addresses the missed Agent handling
