### ISSUE TITLE
Include activitysim trip_id as attribute in BEAM plans

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/beam#3368]
Right now the BEAM urbansim/activitysim csv inputs have a trip_id column. Can we find a way to read this in and store it as a trip attribute that can be output in our plans and some relevant events (mode choice, PersonEntersVehicle, etc.)?

![image](https://user-images.githubusercontent.com/16938242/142292305-6d99ae11-d74e-491f-8c7d-31aa2c916aea.png)

**Comment by Xuan-1998** [comment]
It should be doable, as for the input trip_id, we could probably do the similar thing as we did to InputPlanElements to catch it, try to add trip_id here as well.
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/utils/scenario/urbansim/censusblock/entities/InputPlanElement.scala

And for output them to our events, plans, etc., I think we could utilize the similar process as well:
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/utils/scenario/urbansim/censusblock/entities/OutputPlanElement.scala

There may be some other tricks and more things need to be aware, anyone who is more familiar feel free to correct me. I'm interested in trying to work on this if that makes sense since it’s a good practice to understand beam input and output better as well. @dimaopen Maybe Dima do you want to have a look?

One thing I found tricky is how to get trip_id here: https://github.com/LBNL-UCB-STI/beam/blob/f54e10dd0ee31c5c0183ccffd6dd8449abf03cf8/src/main/scala/beam/utils/csv/writers/PlansCsvWriter.scala#L42-L47
For personId we have `plan.getPerson.getId.toString` to get id but, not sure how to get trip_id yet

**Comment by Xuan-1998** [comment]
Actually, I found a better way to get trip_id, we already have `getPersonInfo`  method which can come pin handy!

**Comment by Xuan-1998** [comment]
![image](https://user-images.githubusercontent.com/58761221/144554674-e5a1154d-a6a8-407e-87c6-be8219b2735e.png)
Was thinking about put `tripId` as an attribute for either `Leg` or `Plan`, but it could not find a way yet

**Comment by dgm90** [comment]
Since this PR we have an error while running a simulation. 
```
07:33:15.153 [main] ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.lang.NullPointerException: null
	at org.matsim.utils.objectattributes.attributable.AttributesXmlWriterDelegate.writeAttributes(AttributesXmlWriterDelegate.java:62)
```
![image](https://user-images.githubusercontent.com/29230919/146948103-8da88864-ab64-4845-a1d8-334dcb3c7eca.png)


This happens because we have `None` as a value for `trip_id` for some persons.



So we need to fix that @Xuan-1998
