### ISSUE TITLE
Tests: the execution time of each test

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3396]
Sometimes after some changes some of tests takes too much time to finish, we need a way to see which tests are taking too long to finish.
There is almost the same issue for CI - sometimes some tests long execution leads for CI to fail because of timeout, we need to understand which tests did not finish in time.

Probably we need one tool for both problems - a way of logging of the start time of each test and finish time (if a test finish with failure or success)

**Comment by JustinPihony** [comment]
Are you looking for a way to tell which tests are running? Or which ones upon completion - because they already do that. As such I am assuming you want the former. For that, we could create a global fixture which would log the start of each test so you could see when it started. Or, we could utilize [the slowpokedetector](https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/tools/Runner.scala#L90) (an undocumented helper) to print out tests that are running for too long (configurable). That would save extra effort and might be a good starting point - then we could move to logging starts if still needed. But realistically, that [comes with the slowpoke too](https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/DispatchReporter.scala#L77) - so configured right it should be what we need.

**Comment by dgm90** [comment]
I would also rework a little bit the test task, so that it gives a list of failed specs in the summary at the end. Right now it is kinda difficult to walk through the entire log trying to find the tests that failed.

**Comment by nikolayilyin** [comment]
> I would also rework a little bit the test task, so that it gives a list of failed specs in the summary at the end. Right now it is kinda difficult to walk through the entire log trying to find the tests that failed.

thanks, here is the issue - https://github.com/LBNL-UCB-STI/beam/issues/3414

**Comment by nikolayilyin** [comment]
> For that, we could create a global fixture which would log the start of each test so you could see when it started. Or, we could utilize the slowpokedetector (an undocumented helper) to print out tests that are running for too long (configurable).

There are two problems I want to solve: 
1. easier way to find tests that became too slow 
2. easier way to find what slow tests caused CI to timeout

The perfect solution would be to test not only things that each test tests but also to check that execution time of each test is exactly what we expect. This way we might even catch all changes that causes simulation to be slower. But fine tuning of each test execution time might be difficult and time consuming.
