### ISSUE TITLE
Second Router doesn't work as expected

### ISSUE THREAD

**Issue by g-derzhavets** [LBNL-UCB-STI/beam#3469]
This issue came from the [NYC branch](https://github.com/LBNL-UCB-STI/beam/pull/3109), that is already merged into develop.

The expected way for the second router was: we have two directories - `r5-train-only` and `r5-bus-only` with two different gtfs files each (`train.zip` and `bus.zip`). We create a config and set the `beam.routing.r5.directory` and `beam.routing.r5.directory2` pointing to those two directories respectively. 
When we run the simulation now we get an exception from the network. The reason for this exception is that there are 2 network files generated (`network.dat` and `physsim-network.xml`) and these files are not the same for each of our 2 directories (routers). This causes a problem in the simulation.

So we did some experiments and the only way to make the second router work (and produce trips for the second transport - bus) that we found is the following:

- Run the simulation with 1 router (but with 2 gtfs files - train and bus).
- The simulation produces proper `network.dat` and `physsim-network.xml`. Proper here means there are trips both for train (subway) and bus.
- Manually copy those files into our 2 folders - `r5-train-only` and `r5-bus-only`
- Run the simulation with two routers and meet success (we have passengerPerTrips graphs both for the train and for the bus and we have non-zero passengers on them).

So the goal for this issue is to elaborate the requirements for the second router and to change the code to meet these requirements.

The file to work on - `beam/router/r5/NetworkCoordinator.scala`

**Comment by dimaopen** [comment]
I researched this issue and found the original way how the second router is supposed to work.
1. The **first r5** directory must contain all the gtfs files we want to use during the simulation. Or these vehicles are not presented in the city.
2. The **second r5** dir should contain only those gtfs files that we want the router to provide more frequently (i.e. subway).

The vehicles of those gtfs files that aren't in the **first r5** dir will not go around the city. Even if the second router provides these itineraries the persons couldn't get to the vehicle because there's no that vehicle.

**Comment by dimaopen** [comment]
I researched this issue and found the original way how the second router is supposed to work.
1. The **first r5** directory must contain all the gtfs files we want to use during the simulation. Or these vehicles are not presented in the city.
2. The **second r5** dir should contain only those gtfs files that we want the router to provide more frequently (i.e. subway).

The vehicles of those gtfs files that aren't in the **first r5** dir will not go around the city. Even if the second router provides these itineraries the persons couldn't get to the vehicle because there's no that vehicle.

**Comment by g-derzhavets** [comment]
Maybe we should add a Readme about it? So our ancestors won't waste time on trying to figure out how to run the two routers @dimaopen

**Comment by dimaopen** [comment]
I'll add this info during work on the issue https://github.com/LBNL-UCB-STI/beam/issues/3378
