### ISSUE TITLE
Preparations for clean-up of AWS storage: bucket analysis

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3612]
We need to analyze what data we have in the beam bucket on AWS S3 - there are lots of historical data and probably not all of them are useful. 
There is a script somewhere in the beam code, probably in python, that is able to do the reading of the whole beam bucket.
The result of analysis should be grouped somehow (probably we need to exclude the output files included in the simulations spreadsheet, this is an issue #3611 or mark them somehow) in order to ease decision making about keeping them or deleting. 
A possible way of grouping - by path and\or date and\or size

**Comment by rajnikantsh** [comment]
@nikolayilyin  please refer this. https://github.com/LBNL-UCB-STI/beam/tree/develop/aws/src/main/python/s3BucketList

**Comment by nikolayilyin** [comment]
@rajnikantsh thanks!

**Comment by edwazhao** [comment]
Hi @nikolayilyin , I have finished the shell script, here is the script and output result.
[s3_beam_outputs.txt](https://github.com/LBNL-UCB-STI/beam/files/10022603/s3_beam_outputs.txt)
[analysis_s3_bucket.sh_rename.txt](https://github.com/LBNL-UCB-STI/beam/files/10022609/analysis_s3_bucket.sh_rename.txt)

I got two questions:
1. Where should I put of the shell script to the beam project? For the file name of shell script above, please rename it because the github doesn't allow to upload sh file
2. The total execution time is more than 10 hours due the calculation of the folder size is too much time comsuming. If there need some update, can I lunch a simple EC2 to run the shell?
