### ISSUE TITLE
Preprocessing Network

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#53]
Complete preprocessing of R5/MATSim networks and integrate into BEAM codebase.

GanttStart: 2017-08-06
GanttDue: 2017-08-14

**Comment by neverforgit** [comment]
My R5 to MATSim class beam.agentsim.r5Extractor.MNetFromR5 compiles and runs, but there is some bizarre stuff happening. Whole swaths of San Francisco are missing. I believe it is because I wrote it such that, if a link is not found in the OSM.mapdb that R5 creates, then I skip it since we don't the link attributes (number of lanes, highway classification). 

Perhaps I am not building the original R5 network correctly? Maybe there is a flag to save all OSM ways into the mapdb database.

Decided to switch to building the test network to try and wrap my head around how R5 parses the OSM files. I (almost) have class that makes the manhattan street grid in OSM's xml format. Still need to synthesize the GTFS for the lines we talked about.

**Comment by neverforgit** [comment]
The OSM test network seems to be working. This is a simple 5x5 square grid. It satisfies the JOSM network validation tool with warnings regarding overlapping highways. In this version, each side of the street is a oneway=true way (i.e. separate directed link), but both directions share the same end nodes. 

https://drive.google.com/open?id=0B5DYEo0XCyF6YlZkYUhHOHZPR1E

**Comment by neverforgit** [comment]
Version_2, now with separate ways for each direction is almost done. I just need to tweak it to put the (0,0) origin in the lower left.

![image](https://user-images.githubusercontent.com/4992903/29391496-99f22a9a-82ac-11e7-82e1-ee861e3167e8.png)

**Comment by neverforgit** [comment]
Newest version, see #60 for discussion.

https://drive.google.com/open?id=0B5DYEo0XCyF6ajEwdWcxbHlpaU0

**Comment by neverforgit** [comment]
@colinsheppard clarifying question, does this issue include creating the _transit routes_? I guess the answer is yes.

**Comment by colinsheppard** [comment]
Yes.

**Comment by colinsheppard** [comment]
After some debugging, discovered that:

- When we process the EdgeStore, there are many links missing, e.g. including the Bay Bridge
- We have determined that the problem is not with osmlib, all links appear to be loading into the MapDB fine
- Hypothesis is that during island pruning, these links are getting wrapped into an island and are thrown out
- Another, less likely, hypothesis is that turn restrictions is the cause
