### ISSUE TITLE
Integrate AgentSim -> PhysSim -> Router Data Flow

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#56]
Create event handling / aggregation actors that listen for appropriate events from BeamVehicles (or more likely from BeamAgents driving Vehicles) and construct the corresponding MATSim plans. The resulting plans should either be passed to PhysSim in memory or written to / loaded from disk.

GanttStart: 2017-08-14
GanttDue: 2017-08-25

**Comment by wrashid** [comment]
Subtasks which need to be implemented in order to complete the bigger integration task:

1.) create plans from AgentSim events for both road and pt vehicles 
2.) when AgentSim ends, it sends StartPhysSimMessage with plans to PhysSim (it is assumed JDEQSim receives road network during initialization). To test we can load it from a MATSim config, which would be replaced in future by network loaded through BEAM config. 
3.) Integrate JDEQSim actor into the pipeline
4.) Integrate EventManager/-Bus actor into pipeline (allow subscribing for handlers).
5.) create and integrate handler for creating TTMatrix for specified bin size
6.) send TTMatrix to Router
7.) update street layer times immediatly in router (and any child actors)

For commands sent between AgentSim, PhysSim and Router, implement the to be introduced interface AkkaCommand { Object getContent(); }

**Comment by wrashid** [comment]
updating pt travel times will be done separately (from agentSim to router).

**Comment by wrashid** [comment]
First version of full integration is completed (AgentSim -> PhysSim Data Flow to Integrate AgentSim). 
Next working on optimizations and code refactorings: how to best shallow copy transportNetwork.
