### ISSUE TITLE
read matsim plan from csv

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#635]

**Comment by mr-asif-nor** [comment]
please integrate in beamhelper (-> just remove old param from matsim and add beam.agentsim.agents.population.beamPopulationFile).

**Comment by colinsheppard** [comment]
@mr-asif-nor so far, so good.

But there is more to do on reading plans from CSV.

First, please make the reader capable of accepting plans either in .csv or in .csv.gz format and use a gzip extractor as appropriate. 

Second, we need to read a second file that will look like this and convert the appropriate data into what BEAM expects from the personAttributes file:

person_id,member_id,age,primary_commute_mode,relate,edu,sex,hours,hispanic,earning,race_id,student,work_at_home,worker,household_id,node_id_small,node_id_walk,job_id
0,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,0,65468916.0,5125306423.0,413751.0
1,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,670,286130668.0,5265127525.0,31870.0
2,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,740,2279076090.0,286097004.0,1258351.0
3,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,975,3969450575.0,65466727.0,343693.0
4,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,977,65615509.0,65548530.0,447704.0
5,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,2321,353140136.0,65554417.0,193894.0
6,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,2785,,,
7,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,2790,281149293.0,4624409119.0,72660.0
8,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,2800,281149293.0,5262829277.0,332958.0

**Comment by colinsheppard** [comment]
Actually, the loading process is more complicated. We need to be able to create all four files, plans, personAttributes, household, householdAttributes, from an archive that contains the following CSV files. These are all related, so we want this controlled by one overall class / method, but it can call other classes each designed to load one of the four data types.

Note, in order to get the x/y of a household, you have to join several of these tables: 
hhhouseholds_v2.unit_id -> units_v2.building_id -> buildings_v2 -> pacel_id -> parcel_attr.xy

==> buildings_v2.csv <==
building_id,parcel_id,development_type_id,improvement_value,residential_units,residential_sqft,sqft_per_unit,non_residential_sqft,building_sqft,nonres_rent_per_sqft,res_price_per_sqft,stories,year_built,redfin_sale_price,redfin_sale_year,redfin_home_type,costar_property_type,costar_rent,building_type_id
1.0,742974.0,1.0,0.0,1.0,2029.0,2029.42425042,0.0,2029.42425042,0.0,302.769750709,1.0,1945.0,,,,,,1.0
2.0,744961.0,1.0,0.0,1.0,2029.0,2029.42425042,0.0,2029.42425042,0.0,254.429278918,1.0,1965.0,,,,,,1.0

==> households_v2.csv <==
household_id,serialno,persons,building_type,cars,income,race_of_head,hispanic_head,age_of_head,workers,state,county,tract,block_group,children,tenure,recent_mover,block_group_id,single_family,unit_id,building_id
0,2010000487191,1,6.0,1.0,85000.0,1,no,47,1.0,6,85,500901,1,0.0,2,0,60855009011,False,1711366,409174.0
1,2013000554587,1,9.0,1.0,27000.0,6,no,52,1.0,6,85,500901,1,0.0,2,0,60855009011,False,1711818,1579443.0

==> parcel_attr.csv <==
primary_id,development_type_id,land_value,acres,county_id,zone_id,proportion_undevelopable,tax_exempt_status,apn,parcel_id_local,geom_id,imputation_flag,x,y,shape_area,block_id,node_id
229116,1,0.0,3.36052039813,1,725,0.0,0,099 029001700, ,10305106092872,_,-121.795620290461,37.6553791330532,13599.555578376372,060014511022061,53091636
244166,1,0.0,1.29442276132,1,715,0.0,0,099B540210200, ,11107351665227,_,-121.71300393197,37.717276807559,5238.3476958754545,060014511011025,53059159

==> persons_w_jobs.csv <==
person_id,member_id,age,primary_commute_mode,relate,edu,sex,hours,hispanic,earning,race_id,student,work_at_home,worker,household_id,node_id_small,node_id_walk,job_id
0,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,0,65468916.0,5125306423.0,413751.0
1,1,47,1.0,0,22.0,1,40.0,1,85000.0,1,0,0,1,670,286130668.0,5265127525.0,31870.0

==>  units_v2.csv <==
unit_id,building_id,num_units,tenure,unit_num,unit_residential_price,unit_residential_rent
0,1,1,1,0,0,0
1,9,1,1,0,0,0

==>  plans.csv <==
personId,planElement,planElementIndex,activityType,x,y,endTime,mode
0,activity,1,Home,-121.88227690977199,37.339126477768296,10.25434663,
0,leg,2,,,,,drive

**Comment by colinsheppard** [comment]
@mr-asif-nor some additional thoughts.

--- We need to add age, sex, value of time, rank, available-modes to Person attributes or customizableAttributes (as appropriate)
--- value of time will need to be sampled within BEAM... @colinsheppard will post more info on how to do this soon.
--- rank should be in reverse order of age (higher age means lower rank, so oldest member of household has rank 0, youngest member has the highest rank)
--- available-modes should be just a default of all modes: car,ride_hail,bike,bus,funicular,gondola,cable_car,ferry,tram,transit,rail,subway,tram

--- for housholds, we need to set vehicles, income, and home location:
--- for income, grab from household.csv file
--- for vehicles, create new vehicles based on field in household file use default vehicle type for CAR, colin will provide more info on how to sample the vehicle type
--- for household coordinate, see above comment on how to get to that data but also make sure we transform the coordinate from WGS84 to local CRS (use wgs2Utm in beamServices.geo utility).

**Comment by colinsheppard** [comment]
More info for you. The plan for the file names is to be minimal (no added "_v2" etc.). So like this:

units.csv, plans.csv, persons.csv, parcel_attr.cvs, households.csv, buildings.csv

You can rename the test data to the above for using in development.

**Comment by mr-asif-nor** [comment]
Ok. I have taken the data from above comment and put it into files.
