### ISSUE TITLE
Find out how to Use Inheritance with Id of Consider Dropping use of MATSim Id Class

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#66]
Id types are helpful but limited when we want to generically store a supertype of Ids. In our case, we would like to store a BeamAgent Id regardless of whether it is actually a PersonId or a VehicleId, etc. My first attempt to do this was unsuccessful, here's where we'd ideally do it instead of converting to string:

BeamSim.resetPop:
```
    services.personRefs.foreach{case(id, ref) =>
      services.agentRefs = services.agentRefs + (id.toString() -> ref)
    }
```

**Comment by dserdyuk** [comment]
@colinsheppard I have also faced with it. Just keep in mind that  Id.equals implemented using `compare() == 0` which uses Id.toString() anyways

**Comment by colinsheppard** [comment]
@dserdyuk Right, so even if there was a way to use inheritance with generics to allow a collection of Id[BeamAgent], we still have to actively work to ensure that Id's are unique across types... this can only be enforced through convention, not type safety.

So as long as we're relying on convention, we should consider String Ids that always start with the type "person-1", "vehicle-1", and a programming convention to avoid variable names like "id" in favor of "personId" or "beamAgentId".

**Comment by sfwatergit** [comment]
RE: https://github.com/lucastorri/idid

> On typed ids, I can't tell from the README if this allows us to have a typed id hierarchy (i.e. can PersonId and VehicleId both extend from BeamAgentId?) and we would need to think through how these would interact with MATSim Id<?> class and whether the conversions back and forth there are worth the benefit we might get from this system.

I think we can come up with a way to do this automatically with implicits the way I've been doing this now w/ Id[Person] and Id[PersonAgent]. 

As for benefit, I see one, since I've had to add some hacks to the RideHailingAgent to create ad-hoc Ids matching a naming convention

Hierarchy could likely be done using type constraints, though I haven't played with it. It's not an ASAP project... I'll add as something to consider on the issue convo.

**Comment by michaz** [comment]
Those Ids are part of the MATSim API -- I'd suggest to use them for identifying MATSim entities, and only those. No need to adopt that type in the agentsim.

**Comment by sfwatergit** [comment]
@michaz this would imply a rather concerted refactoring effort. I don't see too much of a problem with MATSim Ids because wherever there are constraints on interconversion between semantically equivalent classes (such say Id[Person] vs  Id[PersonAgent]), I've written some implicit conversions to automate the task). As above, I still find these Identifiers useful, as it reduces the temptation to rely on regexp matching for string type identifiers in a variety of use-cases. Could you make an argument for removing them?

**Comment by michaz** [comment]
I don't have one, as long as they are not in anyone's way. I thought they were, because that's what this ticket implies. I just meant that there's also not any argument *for* using them, from my side.

**Comment by sfwatergit** [comment]
Well, about actor refs, they are separate entities entirely. I do see some sense in having consistent prefix naming if only to have actor names make sense in the logs. However, we still usually need to keep the ids with the actors because they aren't typed. We haven't been doing this so consistently, which is part of the reason we have this nasty beamServices mega object floating around. I totally agree at this point that it needs to be slimmed down to only the route, scheduler, and maybe config paramet. That's a separate item though.
