### ISSUE TITLE
Summary Stats Collection and Writing

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#835]
We want to collect summary stats across both agentsim and physsim.

Right now in BeamSim (lines 109-126) we separately create the object that runs the physsim (agentSimToPhysSimPlanConverter) which internally collects stats and creates graphs and one that collects stats and creates graphs from the agentsim: createGraphsFromEvents.

Without changing how these are working, I'd like to add a method to each of these, getIterationSummaryStats: Map[String,Double] which will simply return some set of aggregate statistics summarizing the full iteration.

Then in BeamSim at the end of each iteration, please collect these summary stats from both agentsim and phhysism (note, only collect from physsim if skipPhysSim is FALSE) and write to CSV with format:

iteration,<stat name 1>,<stat name 1>,....
1,<value 1>,<value 2>,....
2,<value 1>,<value 2>,....

I will add more comments to this issue soon describing the actual stats to collect and return from getIterationSummaryStats.

**Comment by zishanbilal** [comment]
The idea is that those stats will be aggregated into a single metric, or maybe into a vector of metrics (e.g. instead of a single value for VMT, maybe we would do vmtBike, vmtCar, vmtBus).

Sstart with CarVehicleMilesTravelled as a first Number and CarTotalTravelTime. Add BusVehicleMilesTravelled, we also need BusPassengerMilesTravelled.
