### ISSUE TITLE
Ensure AttributesOfIndvidual has all needed attributes for computations

### ISSUE THREAD

**Issue by sfwatergit** [LBNL-UCB-STI/beam#880]
It seems some attributes don't get moved into AoI due to some strange MATSim inconsistencies (e.g., personAttributes vs. customAttributes). We should use the AoI as a single source of truth for these regardless of what source they come from.

**Comment by colinsheppard** [comment]
The problem: it's challenging to keep track of all the demographic data that is or is not specified in the personAttributes and householdAttributes files because they are unstructured. If data are missing, they sometimes take on unexpected values inside the model without warning or error. E.g. if age is missing from personAttributes, agents are effectively assumed to be infants (age 0) resulting in strangeness.

Solution: we will still allow data to be provided to BEAM using personAttributes and householdAttributes BUT we will create a default method in the trait PopulationAdjustment that does the following (i.e. we want this process to always happen regardless of the specific implementing class that is used):

Move all data from the customAttributes hashmap into AttributesOfIndividual and AttributesOfHousehold. Validate the data as we move it. If data are missing either fail (if critical data) or give a warning and assume a default value (preferred option).

Finally, expunge/unlink the customAttributes maps and then refactor all places in BEAM where it is currently used in favor of using AttributesOfHousehold / AttributesOfIndividual.

**Comment by sfwatergit** [comment]
No need to add this method to populationAdjustment... it can be used as alternative "apply" constructor in AttributesOfIndividual case class, right?

**Comment by colinsheppard** [comment]
sure, but once the data gets into AoI it would be good to delete the redundant data from Population... this would be appropriately done as a setup task in PopAdjust

**Comment by sfwatergit** [comment]
Ok. Fixed. Moved all of the attribute loading usually done in household to PopAdjust. We'll probably want to ensure it gets run regardless of how many agents are specified. I'm not 100% sure of the intent of this class, so if you want to fix it in a separate PR, let's do that (or if it's very quick, let's put in this one).
